// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrUPm3MNXKdr2BNjlBpNpIjZOR7niztrM',
    appId: '1:438279078908:web:16de835fda11b515752879',
    messagingSenderId: '438279078908',
    projectId: 'my-transpostbus-project',
    authDomain: 'my-transpostbus-project.firebaseapp.com',
    storageBucket: 'my-transpostbus-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9jArklg27kF5BuJaSH0EfgrapCqOruz8',
    appId: '1:438279078908:android:ef4bff71200a9ac5752879',
    messagingSenderId: '438279078908',
    projectId: 'my-transpostbus-project',
    storageBucket: 'my-transpostbus-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCjdxEz3j48LngV0ntIeJrvnOO5OReQVo',
    appId: '1:438279078908:ios:a395307b7d5ef826752879',
    messagingSenderId: '438279078908',
    projectId: 'my-transpostbus-project',
    storageBucket: 'my-transpostbus-project.firebasestorage.app',
    iosBundleId: 'com.service.transportServiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCjdxEz3j48LngV0ntIeJrvnOO5OReQVo',
    appId: '1:438279078908:ios:a395307b7d5ef826752879',
    messagingSenderId: '438279078908',
    projectId: 'my-transpostbus-project',
    storageBucket: 'my-transpostbus-project.firebasestorage.app',
    iosBundleId: 'com.service.transportServiceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrUPm3MNXKdr2BNjlBpNpIjZOR7niztrM',
    appId: '1:438279078908:web:85ae7dde45a004a5752879',
    messagingSenderId: '438279078908',
    projectId: 'my-transpostbus-project',
    authDomain: 'my-transpostbus-project.firebaseapp.com',
    storageBucket: 'my-transpostbus-project.firebasestorage.app',
  );
}
